### PR TITLE
Use correct value for timetic 

### PR DESCRIPTION
**Pull request by StephenTerry**
I think the wrong value for timetic is being used. I believe the correct version is written in column 4 of the data rows. Using this value from the final data row, and including the gain in the calculation, I get integrated_dose to match the Corrected data as seen in the Profiler app.

### CODE REVIEW

**Comment by jrkerns** [comment]
Would you mind sending me the file you used and a screenshot of the profiler result? I'd like to add a test for it. Thanks

**Comment by StephenTerry** [comment]
Here you go. This fix gets the flatness and symmetry values a little
closer. I've noticed the interpolation returns slightly different values
for each point which may explain the rest of the difference in F&S.

**Comment by jrkerns** [comment]
Sorry, I forgot about this. I'll be working on this this week. Thanks

**Comment by jrkerns** [comment]
I looked at the results for ~650 .prm files I have and the differences are small IMO except one or two configs. 

image

**Comment by StephenTerry** [comment]
James,

Sorry it took so long to get back to you on this. My results agree with
yours. They are very close to the results from the Profiler software.
Thanks for making this change.

Steve

**Pull request merged**
