### PR TITLE
Created offset calculations for Catphan604

### LINKED ISSUE #289: CBCT HU Uniformity auto slice detectionn
**Describe the bug**
Catphan 604 HU Slice not correctly picking center of module 

**To Reproduce**
1. How Do I provide you my dataset?
1. Run Catphan 604 analysis with defaults according to documentation

**Expected behavior**
The slice width wires should show in the center of the blue detection regions 

**Screenshots**
CT_m011_d30_Head_result_hu
It's hard to see but the slice width wires are at the edges of the detection region, looks like the slice selected was too close to the air region of the phantom
CT_m01_d14_Pelvis_result_hu
This is consistent over a wide selection of our datasets. 

This issue is probably also contributing to our inconsistent measured slice width

### PR DESCRIPTION
**Pull request by crcrewso**
HU linearity module differences, Fixes #289

### CODE REVIEW

**Comment by crcrewso** [comment]
Closed was due to me trying to track down an error message. This was caused not by the code but by the way I was testing it. Code change should work well

**Comment by jrkerns** [comment]
Okay so I tested this on a few more datasets, but they're all Varian so I'd like to ensure this works on other vendors' sets. I added some clarifications.

**Comment by crcrewso** [comment]
I had removed the distal slice because it looked like there was about 2 mm of contrast material past the end of the wire on that end. 

Why is the step size hard coded? What does that number represent? 

I have access to GE CT data sets and Varian CBCT. I wonder if anyone has used the phantom with Elekta or if they come with a different phantom.

**Comment by crcrewso** [comment]
I'm looking at the most recent version and it's pulling the slice one or two more proximal(?) than center. 

Also, based on these image sets I'm wondering if the ROI diameter should be reduced to 4.5 mm to ensure that the ROI is always within the Contrast material. Some of those ROI's are right at the boundary. 

Oasis_m02_d10_Pelvis_result_hu
Oasis_m02_d10_Thorax_result_hu
Oasis_m02_d10_Head_result_hu
CT_Ref_Pelvis_hu
CT_Ref_Head_hu

**Comment by jrkerns** [comment]
After thinking about this I believe you'll be pretty happy with v2.4 and that this problem is an X/Y problem. Elekta comes with the CatPhan 503 (or used to; I haven't kept up). 

-The step size is 2 as a performance hack. The step size is...well, the step size. Using a value of 2 means it looks at every other slice as it walks through the stack. This makes the analysis ~50% faster. 
-It does indeed look like the contrast ROIs extend past the end of the ramp for the 604. this is why the "central" slice appears off w.r.t the ramp; it's the center of the contrast ROIs, not the ramp. I'm not sure this is actually a problem though. The ramp is consistent throughout its slices, so an evaluation +/- one or two slices should be consistent.
-In 2.4 you'll be able to construct your own phantom models and can offset the spatial resolution slice offset if desired. 
-You can override the ROI size to your liking. You can see the upcoming documentation here: https://pylinac.readthedocs.io/en/latest/cbct_docs.html#customizing-module-locations. 

Does this solve your problem?

**Comment by crcrewso** [comment]
I tried to test your most updated code base but I cannot seem to see any differences. Is there any way you could actually make your develop branch public so I could test against that?

**Comment by crcrewso** [comment]
I'm looking at the repository and I can't see the version 2.4 you've referenced. Is there a hidden branch I'm not able to see?

**Pull request closed without merging**
