### PR TITLE
Update reference for TPR20,10 from PDD20,10

### PR DESCRIPTION
**Pull request by mchamberland**
This will save someone a minute or two when looking for the equation in TRS-398.

### CODE REVIEW

**Comment by jrkerns** [comment]
Thanks for adding that clarification. However, my first hit on google takes me here: http://www-naweb.iaea.org/nahu/dmrp/documents/cop_v12_2006-06-05.pdf and it's on page 62 there: 
image. Is there an update to like for TG-51 that I'm missing?

**Comment by jrkerns** [comment]
Maybe. Mine has a disclaimer: 
image
but given the equation is 6 pages later that means there's more content in yours?? Either way, the equation is the same. Just put your URL in the docstring so it's consistent please. Thanks!

**Comment by mchamberland** [comment]
@jrkerns I added the URL to the PDF and I removed k_elec from the TG51ElectronModern docstring, since it appears to have been mistakenly included.

**Comment by jrkerns** [comment]
I'll merge this in tomorrow. Thanks!

**Pull request merged**
